name: infou
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  webview_flutter: ^4.7.0

  google_fonts: ^5.1.0 #수정
  image_picker: ^1.0.4
  simple_gradient_text: ^1.2.4
  uuid: ^3.0.7
  get: ^4.1.4
  quiver: ^3.2.1
  http: ^1.1.0
  dio: ^5.0.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^5.0.2
  kakao_flutter_sdk: ^1.6.1
  kakao_flutter_sdk_user: ^1.6.1
  syncfusion_flutter_gauges: ^23.2.4
  flutter_typeahead: ^5.0.1
  syncfusion_flutter_charts: ^23.2.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  blur: ^3.1.0
  persistent_bottom_nav_bar: ^5.0.2
  page_transition: ^2.1.0
  google_sign_in: ^6.2.1
  firebase_core: 2.27.0
  flutter_widget_from_html: ^0.14.11
  flutter_inappwebview: ^6.0.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/infou_logo.png
    - assets/images/logo.png
    - assets/images/gold_star.png
    - assets/images/grey_star.png
    - assets/images/notice_icon.png
    - assets/images/mypage_icon.png
    - assets/images/evaluate_icon.png
    - assets/images/pig.png
    - assets/images/review.png
    - assets/images/major.png
    - assets/samples/ad_sample1.png
    - assets/samples/ad_sample2.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-oPs.png
    - assets/page-1/images/vector-pdj.png
    - assets/page-1/images/vector-KcH.png
    - assets/page-1/images/vector-SeR.png
    - assets/page-1/images/vector-zPf.png
    - assets/page-1/images/vector-vo7.png
    - assets/page-1/images/vector-5vu.png
    - assets/page-1/images/vector-UNq.png
    - assets/page-1/images/mingcute-pig-money-line.png
    - assets/page-1/images/chevron-right.png
    - assets/page-1/images/vector-1EM.png
    - assets/page-1/images/vector-K6d.png
    - assets/page-1/images/vector-sqX.png
    - assets/page-1/images/vector-JSh.png
    - assets/page-1/images/chevron-right-rRT.png
    - assets/page-1/images/vector-S8m.png
    - assets/page-1/images/vector-TfT.png
    - assets/page-1/images/chevron-right-Jny.png
    - assets/page-1/images/vector-KCH.png
    - assets/page-1/images/vector-1Gh.png
    - assets/page-1/images/vector-MGh.png
    - assets/page-1/images/vector-SJ9.png
    - assets/page-1/images/vector-sn5.png
    - assets/page-1/images/vector-8WH.png
    - assets/page-1/images/vector-K7T.png
    - assets/page-1/images/vector-tkD.png
    - assets/page-1/images/chevron-right-NEh.png
    - assets/page-1/images/vector-vjP.png
    - assets/page-1/images/vector-Kyo.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/vector-Pbb.png
    - assets/page-1/images/vector-bcR.png
    - assets/page-1/images/vector-Zjb.png
    - assets/page-1/images/image-removebg-preview16-1.png
    - assets/page-1/images/vector-nRB.png
    - assets/page-1/images/vector-XUZ.png
    - assets/page-1/images/chevron-right-drM.png
    - assets/page-1/images/vector-vKf.png
    - assets/page-1/images/chevron-right-WUD.png
    - assets/page-1/images/vector-c2q.png
    - assets/page-1/images/chevron-right-XrV.png
    - assets/page-1/images/chevron-right-mSd.png
    - assets/page-1/images/vector-j5F.png
    - assets/page-1/images/vector-b81.png
    - assets/page-1/images/chevron-right-NCd.png
    - assets/page-1/images/vector-hjs.png
    - assets/page-1/images/vector-hch.png
    - assets/page-1/images/vector-rVb.png
    - assets/page-1/images/vector-zn9.png
    - assets/page-1/images/healthicons-ui-user-profile.png
    - assets/page-1/images/mingcute-pig-money-line-9gy.png
    - assets/page-1/images/vector-TYR.png
    - assets/page-1/images/vector-oZf.png
    - assets/page-1/images/vector-B3j.png
    - assets/page-1/images/vector-8mb.png
    - assets/page-1/images/vector-KFj.png
    - assets/page-1/images/chevron-right-fn5.png
    - assets/page-1/images/vector-koX.png
    - assets/page-1/images/vector-uwK.png
    - assets/page-1/images/back.png
    - assets/page-1/images/vector-4W1.png
    - assets/page-1/images/vector-V65.png
    - assets/page-1/images/mingcute-pig-money-line-Say.png
    - assets/page-1/images/ph-bell-light.png
    - assets/page-1/images/vector-CQM.png
    - assets/page-1/images/vector-gD3.png
    - assets/page-1/images/healthicons-ui-user-profile-uk1.png
    - assets/page-1/images/vector-KuX.png
    - assets/page-1/images/vector-3Lq.png
    - assets/page-1/images/vector-HuP.png
    - assets/page-1/images/chevron-right-Mph.png
    - assets/page-1/images/vector-mgh.png
    - assets/page-1/images/vector-6AR.png
    - assets/page-1/images/vector-DF3.png
    - assets/page-1/images/mingcute-pig-money-line-xGM.png
    - assets/page-1/images/chevron-right-q97.png
    - assets/page-1/images/vector-Wmb.png
    - assets/page-1/images/vector-D6D.png
    - assets/page-1/images/vector-ys3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
