// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwu14RI1r2-4OhNvGVmn9OiOX3gflUe1Q',
    appId: '1:1055588533701:web:a894810b4776cfab65b7ac',
    messagingSenderId: '1055588533701',
    projectId: 'infou-418906',
    authDomain: 'infou-418906.firebaseapp.com',
    storageBucket: 'infou-418906.appspot.com',
    measurementId: 'G-Y1JQHVTXGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUTulJQ_K1jbdl-ZlSwAP6iC8bZXYGydw',
    appId: '1:1055588533701:android:f3403fef0fdaa88c65b7ac',
    messagingSenderId: '1055588533701',
    projectId: 'infou-418906',
    storageBucket: 'infou-418906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD3ynEwd3WsDyLMvTvJmrSBYgz95OQ2bA',
    appId: '1:1055588533701:ios:29e542650a1ef1e165b7ac',
    messagingSenderId: '1055588533701',
    projectId: 'infou-418906',
    storageBucket: 'infou-418906.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD3ynEwd3WsDyLMvTvJmrSBYgz95OQ2bA',
    appId: '1:1055588533701:ios:29e542650a1ef1e165b7ac',
    messagingSenderId: '1055588533701',
    projectId: 'infou-418906',
    storageBucket: 'infou-418906.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
